image: node:16

default:
  cache:
    paths:
      - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
